name: security-action
on:
  push:
    branches: [feature/veracode-scan]

jobs:
  build:
    name: build
    runs-on: macos-latest 
    steps:
    - uses: actions/checkout@v4
    - name: veracode gen-ir and XCode build
      run: |
        echo "# Add the brew tap to your local machine"
        brew tap veracode/tap 
        
        echo "# Install the tool"
        brew install gen-ir 
        
        echo "xcode build"
        xcodebuild clean
        xcodebuild archive -project FSNotes.xcodeproj -scheme FSNotes -configuration Debug -destination generic/platform=macOS -archivePath FSNotes.xcarchive DEBUG_INFORMATION_FORMAT=dwarf-with-dsym ENABLE_BITCODE=NO > build_log.txt
        
        echo "veracode gen-ir"
        gen-ir build_log.txt FSNotes.xcarchive
        
        echo "zip xarchive"
        zip -r FSNotes.zip MyApp.xcarchive
        zipinfo FSNotes.zip